# Generates the UI's contrib manifest: the metadata every enabled contrib
# contributes to the frontend, as ONE TypeScript module the UI compiles.
#
# Build-time, not a runtime API, for two independent reasons: the brand icons are
# React components imported per-icon "so only the ones we use are bundled"
# (ui/src/sourceIcon.tsx), so an icon named as a string at runtime would mean
# bundling all of react-icons; and the UI is a static vite dist/ with no module
# loader, so anything a contrib contributes must exist when vite runs.
#
# The output is committed at ui/src/contribManifest.generated.ts for the repo's
# own contrib set (so `npm run dev`/vitest work outside nix; `just
# contrib-ui-check` fails on drift). A deployment with a different contrib set
# substitutes its own via ui/default.nix's `contribManifest`. Why: PR #601.
{ lib, writeText }:

let
  packs = import ./ui-icon-packs.nix;
  q = builtins.toJSON;
  asc = lib.sort (a: b: a < b);

  # An empty attrset renders as `{}`; a populated one gets its own lines.
  block = lines: if lines == [ ] then "" else "\n" + lib.concatStringsSep "\n" lines + "\n";
in

contribs:

let
  withUi = lib.filterAttrs (_: c: c.ui.enable) contribs;
  sourced = lib.filterAttrs (_: c: c.ui.source != null) withUi;

  icons = lib.mapAttrsToList (_: c: c.ui.source.icon) sourced;
  importLine = pack:
    let names = asc (lib.unique (map (i: i.name) (lib.filter (i: i.pack == pack) icons)));
    in "import { ${lib.concatStringsSep ", " names} } from ${q packs.${pack}};";
  # Trailing newline folded in here so the zero-contrib manifest (a deployment
  # with no UI contribs at all) has no stray blank line.
  imports = lib.concatMapStrings (p: importLine p + "\n") (asc (lib.unique (map (i: i.pack) icons)));

  sourceLines = lib.mapAttrsToList
    (n: c: "  ${q n}: { label: ${q c.ui.source.label}, Icon: ${c.ui.source.icon.name}, color: ${q c.ui.source.color} },")
    sourced;

  # Keyed by the tool NAME (the stable identity the UI normalizes an incoming
  # ACP tool call down to). `provider` is the contrib name, so the card picks up
  # that contrib's source row.
  toolLines = lib.concatLists (lib.mapAttrsToList
    (n: c: lib.mapAttrsToList
      (tool: t: "  ${q tool}: { provider: ${q n}, argKey: ${q t.argKey}, action: ${q t.action} },")
      c.ui.tools)
    withUi);

  # Lowercased: the UI matches a registerTool title case-insensitively.
  titleLines = lib.concatLists (lib.mapAttrsToList
    (_: c: lib.concatLists (lib.mapAttrsToList
      (tool: t: map (title: "  ${q (lib.toLower title)}: ${q tool},") t.titles)
      c.ui.tools))
    withUi);

  linkProviders = lib.attrNames (lib.filterAttrs (_: c: c.ui.source.linkProvider) sourced);
in

writeText "contribManifest.generated.ts" ''
  // @generated by `just contrib-ui-generate` from the enabled contrib set — do not edit.
  // Regenerate after changing a contrib's `ui` options; CI fails on drift
  // (just contrib-ui-check).
  //
  // The committed copy is the manifest for THIS repo's contrib set, so the UI
  // builds outside nix. A deployment enabling a different set gets its own,
  // substituted into the build (ui/default.nix). See contrib/ui-manifest.nix.

  import type { ContribSource, ContribToolCard } from "./contribTypes.js";
  ${imports}
  /** Brand row per contrib: merged UNDER the app's own sources (sourceIcon.tsx). */
  export const contribSources: Record<string, ContribSource> = {${block sourceLines}};

  /** Tool-call message cards, keyed by tool name (toolCallView.ts). */
  export const contribToolCards: Record<string, ContribToolCard> = {${block toolLines}};

  /** registerTool titles accepted as a fallback -> the tool name they mean. */
  export const contribToolTitles: Record<string, string> = {${block titleLines}};

  /** Sources offered as sidebar filter chips and "Show:" label modes (sessions.ts). */
  export const contribLinkProviders: readonly string[] = [${lib.concatMapStringsSep ", " q linkProviders}];
''
