# Generates the UI's contrib manifest: the metadata every enabled contrib
# contributes to the frontend, as ONE TypeScript module the UI compiles.
#
# Build-time, not a runtime API, for two independent reasons: the brand icons are
# React components imported per-icon "so only the ones we use are bundled"
# (ui/src/sourceIcon.tsx), so an icon named as a string at runtime would mean
# bundling all of react-icons; and the UI is a static vite dist/ with no module
# loader, so anything a contrib contributes must exist when vite runs.
#
# The output is a DIRECTORY overlaid onto ui/src: the manifest module, plus a
# copy of each contrib's panel sources under contrib/<name>/. Copies, because a
# deployment's contribs live outside this repo entirely — resolving them by
# alias would need a different alias in-tree and out, which is the kind of
# divergence that only shows up in the deployment that matters.
#
# The overlay is committed for the repo's own contrib set (so `npm run
# dev`/vitest work outside nix; `just contrib-ui-check` fails on drift). A
# deployment with a different set substitutes its own via ui/default.nix.
# Why: PR #601, extended for panels in PR #602.
{ lib, writeText, runCommand }:

let
  packs = import ./ui-icon-packs.nix;
  q = builtins.toJSON;
  asc = lib.sort (a: b: a < b);

  # An empty attrset renders as `{}`; a populated one gets its own lines.
  block = lines: if lines == [ ] then "" else "\n" + lib.concatStringsSep "\n" lines + "\n";
in

contribs:

let
  withUi = lib.filterAttrs (_: c: c.ui.enable) contribs;
  sourced = lib.filterAttrs (_: c: c.ui.source != null) withUi;

  icons = lib.mapAttrsToList (_: c: c.ui.source.icon) sourced;
  importLine = pack:
    let names = asc (lib.unique (map (i: i.name) (lib.filter (i: i.pack == pack) icons)));
    in "import { ${lib.concatStringsSep ", " names} } from ${q packs.${pack}};";
  # Trailing newline folded in here so the zero-contrib manifest (a deployment
  # with no UI contribs at all) has no stray blank line.
  imports = lib.concatMapStrings (p: importLine p + "\n") (asc (lib.unique (map (i: i.pack) icons)));

  sourceLines = lib.mapAttrsToList
    (n: c: "  ${q n}: { label: ${q c.ui.source.label}, Icon: ${c.ui.source.icon.name}, color: ${q c.ui.source.color} },")
    sourced;

  # Keyed by the tool NAME (the stable identity the UI normalizes an incoming
  # ACP tool call down to). `provider` is the contrib name, so the card picks up
  # that contrib's source row.
  toolLines = lib.concatLists (lib.mapAttrsToList
    (n: c: lib.mapAttrsToList
      (tool: t: "  ${q tool}: { provider: ${q n}, argKey: ${q t.argKey}, action: ${q t.action} },")
      c.ui.tools)
    withUi);

  # Lowercased: the UI matches a registerTool title case-insensitively.
  titleLines = lib.concatLists (lib.mapAttrsToList
    (_: c: lib.concatLists (lib.mapAttrsToList
      (tool: t: map (title: "  ${q (lib.toLower title)}: ${q tool},") t.titles)
      c.ui.tools))
    withUi);

  linkProviders = lib.attrNames (lib.filterAttrs (_: c: c.ui.source.linkProvider) sourced);

  # Flattened to [{ contrib, panel }] and sorted here, so the tab order is a
  # property of the manifest rather than of attrset iteration at render time.
  allPanels = lib.sort
    (a: b: if a.panel.order != b.panel.order then a.panel.order < b.panel.order else a.panel.id < b.panel.id)
    (lib.concatLists (lib.mapAttrsToList
      (n: c: map (panel: { contrib = n; inherit panel; id = panel.id; }) c.ui.panels)
      withUi));

  # <contrib>/<file.tsx> -> the module specifier the manifest imports. The suffix
  # is dropped and .js appended: the UI is NodeNext-style ESM, where a .tsx
  # module is imported as .js.
  panelImport = p: "./contrib/${p.contrib}/${baseNameOf (toString p.panel.entry)}";
  panelNs = p: "panel_${lib.replaceStrings [ "-" ] [ "_" ] p.contrib}_${lib.replaceStrings [ "-" ] [ "_" ] p.panel.id}";

  panelImports = lib.concatMapStrings
    (p: "import * as ${panelNs p} from ${q (lib.removeSuffix ".tsx" (panelImport p) + ".js")};\n")
    allPanels;

  panelLines = map
    (p: "  { id: ${q p.panel.id}, title: ${q p.panel.title}, usePanel: ${panelNs p}.usePanel },")
    allPanels;

  # The panel sources, laid out as the manifest imports them.
  panelSources = lib.concatMapStrings
    (p: ''
      mkdir -p $out/contrib/${p.contrib}
      cp ${p.panel.entry} $out/contrib/${p.contrib}/${baseNameOf (toString p.panel.entry)}
    '')
    allPanels;

  manifest =

    writeText "contribManifest.generated.ts" ''
  // @generated by `just contrib-ui-generate` from the enabled contrib set — do not edit.
  // Regenerate after changing a contrib's `ui` options; CI fails on drift
  // (just contrib-ui-check).
  //
  // The committed copy is the manifest for THIS repo's contrib set, so the UI
  // builds outside nix. A deployment enabling a different set gets its own,
  // substituted into the build (ui/default.nix). See contrib/ui-manifest.nix.

  import type { ContribSource, ContribToolCard } from "./contribTypes.js";
  ${imports}
  /** Brand row per contrib: merged UNDER the app's own sources (sourceIcon.tsx). */
  export const contribSources: Record<string, ContribSource> = {${block sourceLines}};

  /** Tool-call message cards, keyed by tool name (toolCallView.ts). */
  export const contribToolCards: Record<string, ContribToolCard> = {${block toolLines}};

  /** registerTool titles accepted as a fallback -> the tool name they mean. */
  export const contribToolTitles: Record<string, string> = {${block titleLines}};

  /** Sources offered as sidebar filter chips and "Show:" label modes (sessions.ts). */
  export const contribLinkProviders: readonly string[] = [${lib.concatMapStringsSep ", " q linkProviders}];

'';

  # SEPARATE from the metadata manifest, and that is load-bearing. A panel
  # imports @scooter/ui-kit, which re-exports the app's session store, which
  # reads the metadata manifest for its provider list. One module holding both
  # closes that into an import CYCLE, and the symptom is a TDZ error at module
  # init ("contribLinkProviders is not iterable"), not a compile failure.
  # Metadata stays leaf data; only this module pulls in contrib CODE.
  panelsModule = writeText "contribPanels.generated.ts" ''
    // @generated by `just contrib-ui-generate` from the enabled contrib set — do not edit.
    // Regenerate after changing a contrib's `ui.panels`; CI fails on drift.
    //
    // Kept apart from contribManifest.generated.ts on purpose: importing a panel
    // pulls in @scooter/ui-kit, so merging the two would make the app's own
    // modules depend on contrib code and close an import cycle.

    import type { ContribPanel } from "./contribTypes.js";
    ${panelImports}
    /** Right-panel tabs, already in display order (RightPanel.tsx). */
    export const contribPanels: readonly ContribPanel[] = [${block panelLines}];
  '';
in

# One directory overlaid onto ui/src: the manifest plus the panel sources it
# imports. A single derivation so the two can never be applied out of step.
runCommand "contrib-ui" { } ''
  mkdir -p $out
  cp ${manifest} $out/contribManifest.generated.ts
  cp ${panelsModule} $out/contribPanels.generated.ts
  ${panelSources}
''
