# The shared-database SPEC: which databases exist, which tables live in each, and
# who may write/read them — declared in the module system, by the module that owns
# the service.
#
# TOPOLOGY ONLY. This option does not model columns; DDL stays DDL in
# lib/sql/<db>/schema.sql. Nix owns the facts that have to agree across the
# deployment (which database, who writes, who reads) and nothing else.
#
# Everything downstream is a RENDERING of this option, not a second copy:
#   - lib/sql/owners.toml        generated (`just db-generate`), CI fails on drift
#   - lib/sql/atlas.hcl          generated; one Atlas env per database
#   - the migrator's database list  modules/db-migrate.nix, derived
#   - the postgres GRANTs        modules/platform.nix, derived
#
# There is deliberately NO separate database-list artifact: owners.toml's top-level
# `[<database>]` sections ARE that list, and the justfile + scripts/db-generate.sh
# read it back from there (both need it at shell/parse time, where `nix eval` is too
# expensive to run on every invocation).
#
# The direction used to run the other way: platform.nix read owners.toml with
# `builtins.fromTOML` to derive the conversation-router's grants, "so the grant
# can't drift". This inverts that — the option is the source and the manifest is
# the rendering. Why: issue #606.
#
# Declarations are UNCONDITIONAL (outside each module's `mkIf cfg.enable`): a table
# exists in lib/sql whether or not this deployment runs the service that owns it, and
# db-migrate.nix gates on `postgres.consumers ? key` for what to actually migrate. A
# CONTRIB declaring tables inside `mkIf cfg.enable` is stage 2 of #606 — that is the
# point at which the generated artifacts become deployment-shaped.

{ config, lib, ... }:

let
  inherit (lib) mkOption types;
  cfg = config.agentSandbox;

  # --- owners.toml rendering -------------------------------------------------
  # Hand-rolled rather than pkgs.formats.toml because the manifest's inline-table
  # layout and its per-table comments are the reason anyone reads the file; a
  # generic TOML writer drops both.
  quoteList = xs: "[" + lib.concatMapStringsSep ", " (x: ''"${x}"'') xs + "]";
  pad = width: s: s + lib.fixedWidthString (lib.max 0 (width - lib.stringLength s)) " " "";

  renderTable = width: name: t:
    lib.optionalString (t.note != null)
      (lib.concatMapStrings (l: "# ${l}\n") (lib.splitString "\n" t.note))
    + "${pad width name} = { writers = ${quoteList t.writers}, readers = ${quoteList t.readers} }\n";

  renderDb = name: db:
    let
      names = lib.attrNames db.tables;
      width = lib.foldl' (a: n: lib.max a (lib.stringLength n)) 0 names;
    in
    ''
      [${name}]
      owner = "${db.owner}"

      [${name}.tables]
    '' + lib.concatMapStrings (n: renderTable width n db.tables.${n}) names;

  # --- eval-time validation --------------------------------------------------
  # A `throw` rather than an `assertions` block because kubenix's module system has no
  # NixOS `assertions` option — an assertions block there evaluates as a plain attribute
  # and silently checks nothing (the repo's convention; see platform.nix). Forced by the
  # `dbSpec.*` outputs below, so it fires wherever the spec is actually consumed — the
  # migrator's database list (db-migrate.nix) and `just db-generate` — rather than only
  # in a test that someone has to remember to run.
  problems = lib.concatLists (lib.mapAttrsToList
    (dbName: db: lib.concatLists (lib.mapAttrsToList
      (tName: t:
        let both = lib.intersectLists t.writers t.readers; in
        lib.optional (t.writers == [ ])
          "agentSandbox.db.${dbName}.tables.${tName}: needs at least one writer."
        ++ lib.optional (both != [ ])
          ("agentSandbox.db.${dbName}.tables.${tName}: ${lib.concatStringsSep ", " both} "
            + "is listed as writer AND reader — a writer already implies read access.")
      )
      db.tables))
    cfg.db);

  checked = v:
    if problems == [ ] then v
    else throw ("Invalid agentSandbox.db spec:\n  - " + lib.concatStringsSep "\n  - " problems);

  ownersToml = ''
    # @generated by `just db-generate` from the `agentSandbox.db` module option — do not edit.
    # Regenerate after a change; CI fails on drift (just db-generate-check).
    #
    # For each (database, table): the WRITER services and the read-only READER services.
    # This is the one reviewable place that records who may write what — schema.sql says
    # WHAT the tables are; this says WHO owns them. The DECLARATIONS live next to the
    # module that owns each service (modules/*.nix, `agentSandbox.db.<database>`); the
    # comments below are rendered from each table's `note`.
    #
    # Enforcement:
    #   - Runtime: assert_database()/assertDatabase() (scooter_schema / @scooter/schema)
    #     make a service fail fast if its DSN points at a database it doesn't own.
    #   - Per-database code boundary: a service imports only the database module(s) it
    #     may touch, so it cannot reference another database's tables.
    #   - Manifest integrity: ownership.spec.ts checks this file lists exactly the tables
    #     each schema.sql defines, so the spec and the DDL can't silently diverge.
    #
    # `writers` is a LIST. Most tables have exactly one, but a table with two legitimate
    # writers is modelled as such rather than duplicated across databases.
  '' + lib.concatMapStrings (n: "\n" + renderDb n cfg.db.${n}) (lib.attrNames cfg.db);

  # --- atlas.hcl rendering ---------------------------------------------------
  # One env per database, all five identical apart from the name. Generated for the
  # same reason as the rest: it was a fifth place that had to list the databases.
  atlasEnv = db: ''

    env "${db}" {
      src = "file://${db}/schema.sql"
      dev = var.dev_url
      migration { dir = "file://${db}/migrations" }
      format {
        migrate {
          diff = "{{ sql . \"  \" }}"
        }
      }
    }
  '';

  atlasHcl = ''
    // @generated by `just db-generate` from the `agentSandbox.db` module option — do not edit.
    // Regenerate after a change; CI fails on drift (just db-generate-check).
    //
    // Atlas config for the Scooter shared schemas.
    //
    // Tables are partitioned across per-service databases on one Postgres server, so
    // there is one Atlas env per database, each with its own schema.sql (the desired
    // end-state) and migrations/ dir.
    //
    // Atlas needs a throwaway "dev" Postgres to normalize each schema and compute
    // diffs — NOT the shared/production database and NOT a long-lived one.
    // `just db-migrate` spins an ephemeral local Postgres per env and passes its URL
    // as ATLAS_DEV_URL, so nothing is shared and concurrent runs cannot interfere.

    variable "dev_url" {
      type    = string
      default = getenv("ATLAS_DEV_URL")
    }
  '' + lib.concatMapStrings atlasEnv (lib.attrNames cfg.db);

in
{
  options.agentSandbox = {
    db = mkOption {
      default = { };
      description = ''
        The shared-database spec, keyed by DATABASE name (`webhooks`, `agent_host`, …
        — the directory name under `lib/sql`, not the consumer key). Declared by the
        module that owns the service; everything downstream (the ownership manifest,
        the migrator's database list, the postgres GRANTs) is generated from it.

        Topology only — this does not model columns. DDL stays in
        `lib/sql/<database>/schema.sql`.
      '';
      type = types.attrsOf (types.submodule {
        options = {
          owner = mkOption {
            type = types.str;
            description = ''
              The service that OWNS the database (its Postgres role owns it and the
              db-migrator connects as that role). Co-written databases still have one
              owner; the other writers appear in the per-table `writers` lists.
            '';
          };
          tables = mkOption {
            default = { };
            description = "The tables in this database, keyed by table name.";
            type = types.attrsOf (types.submodule {
              options = {
                writers = mkOption {
                  type = types.listOf types.str;
                  description = ''
                    Services that may INSERT/UPDATE/DELETE. A LIST: a table with two
                    legitimate writers is modelled as such rather than duplicated per
                    database — that duplication is the byoc.remote_agents failure this
                    shape exists to prevent. A writer implies read access, so a writer
                    must NOT also appear in `readers`.
                  '';
                };
                readers = mkOption {
                  type = types.listOf types.str;
                  default = [ ];
                  description = ''
                    Services granted SELECT only. Table-scoped on purpose: a reader
                    must not gain another table's rows just because it shares a
                    database (notably conversation_events, the full transcripts).
                  '';
                };
                note = mkOption {
                  type = types.nullOr types.lines;
                  default = null;
                  description = ''
                    Why this table's ownership is shaped the way it is. Rendered as a
                    comment above the entry in the generated owners.toml, so the
                    reasoning survives generation instead of living only in Nix.
                  '';
                };
              };
            });
          };
        };
      });
    };

    dbSpec = {
      databases = mkOption {
        internal = true;
        readOnly = true;
        type = types.listOf types.str;
        default = checked (lib.attrNames cfg.db);
        description = "Database names in the spec — the atlas envs under lib/sql.";
      };
      ownersToml = mkOption {
        internal = true;
        readOnly = true;
        type = types.lines;
        default = checked ownersToml;
        description = "The rendered lib/sql/owners.toml. Written out by `just db-generate`.";
      };
      atlasHcl = mkOption {
        internal = true;
        readOnly = true;
        type = types.lines;
        default = checked atlasHcl;
        description = "The rendered lib/sql/atlas.hcl (one env per database).";
      };
    };
  };
}
