// @generated by `just contrib-ui-generate` from the enabled contrib set — do not edit.
// Regenerate after changing a contrib's `ui` options; CI fails on drift
// (just contrib-ui-check).
//
// The committed copy is the manifest for THIS repo's contrib set, so the UI
// builds outside nix. A deployment enabling a different set gets its own,
// substituted into the build (ui/default.nix). See contrib/ui-manifest.nix.

import type { ContribSource, ContribToolCard } from "./contribTypes.js";
import { SiGitlab, SiJira } from "react-icons/si";

/** Brand row per contrib: merged UNDER the app's own sources (sourceIcon.tsx). */
export const contribSources: Record<string, ContribSource> = {
  "gitlab": { label: "GitLab", Icon: SiGitlab, color: "#FC6D26" },
  "jira": { label: "Jira", Icon: SiJira, color: "#0052CC" },
};

/** Tool-call message cards, keyed by tool name (toolCallView.ts). */
export const contribToolCards: Record<string, ContribToolCard> = {
  "gitlab_comment": { provider: "gitlab", argKey: "body", action: "commented on GitLab" },
  "jira_comment": { provider: "jira", argKey: "body", action: "commented on Jira" },
};

/** registerTool titles accepted as a fallback -> the tool name they mean. */
export const contribToolTitles: Record<string, string> = {
  "comment on the gitlab mr": "gitlab_comment",
  "comment on the jira issue": "jira_comment",
};

/** Sources offered as sidebar filter chips and "Show:" label modes (sessions.ts). */
export const contribLinkProviders: readonly string[] = ["gitlab", "jira"];
