// @generated by `just contrib-ui-generate` from the enabled contrib set — do not edit.
// Regenerate after changing a contrib's `ui.panels`; CI fails on drift.
//
// Kept apart from contribManifest.generated.ts on purpose: importing a panel
// pulls in @scooter/ui-kit, so merging the two would make the app's own
// modules depend on contrib code and close an import cycle.

import type { ContribPanel } from "./contribTypes.js";
import * as panel_shares_shares from "./contrib/shares/SharesPanel.js";

/** Right-panel tabs, already in display order (RightPanel.tsx). */
export const contribPanels: readonly ContribPanel[] = [
  { id: "shares", title: "Shares", usePanel: panel_shares_shares.usePanel },
];
