// @generated by `just db-generate` from lib/sql/agent_host/schema.sql — do not edit.
// Regenerate after a schema change; CI fails on drift (just db-generate-check).

import { pgTable, index, text, bigint, boolean, jsonb, primaryKey } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"



export const conversations = pgTable("conversations", {
	id: text().primaryKey().notNull(),
	threadId: text("thread_id").notNull(),
	title: text().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	createdAt: bigint("created_at", { mode: "number" }).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	lastActivityAt: bigint("last_activity_at", { mode: "number" }).notNull(),
	model: text(),
	owner: text(),
	parentId: text("parent_id"),
	userTitled: boolean("user_titled"),
	starred: boolean(),
	pendingQueue: jsonb("pending_queue"),
}, (table) => [
	index("conversations_by_activity").using("btree", table.lastActivityAt.desc().nullsFirst().op("int8_ops")),
	index("conversations_by_owner").using("btree", table.owner.asc().nullsLast().op("text_ops")),
]);

export const conversationJobs = pgTable("conversation_jobs", {
	conversationId: text("conversation_id").notNull(),
	jobId: text("job_id").notNull(),
	command: text().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	startedAt: bigint("started_at", { mode: "number" }).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	notifiedAt: bigint("notified_at", { mode: "number" }),
}, (table) => [
	index("conversation_jobs_by_conv").using("btree", table.conversationId.asc().nullsLast().op("int8_ops"), table.startedAt.desc().nullsFirst().op("int8_ops")),
	primaryKey({ columns: [table.jobId, table.conversationId], name: "conversation_jobs_pkey"}),
]);
