// @generated by `just db-generate` from lib/sql/agent_host/schema.sql — do not edit.
// Regenerate after a schema change; CI fails on drift (just db-generate-check).

import { pgTable, index, primaryKey, text, bigint } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"



export const conversationJobs = pgTable("conversation_jobs", {
	conversationId: text("conversation_id").notNull(),
	jobId: text("job_id").notNull(),
	command: text().notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	startedAt: bigint("started_at", { mode: "number" }).notNull(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	notifiedAt: bigint("notified_at", { mode: "number" }),
}, (table) => [
	index("conversation_jobs_by_conv").using("btree", table.conversationId.asc().nullsLast().op("int8_ops"), table.startedAt.desc().nullsFirst().op("int8_ops")),
	primaryKey({ columns: [table.jobId, table.conversationId], name: "conversation_jobs_pkey"}),
]);
