// @generated by `just db-generate` from lib/sql/broker/schema.sql — do not edit.
// Regenerate after a schema change; CI fails on drift (just db-generate-check).

import { pgTable, varchar, text, index, uniqueIndex, serial, integer } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"



export const sandboxSize = pgTable("sandbox_size", {
	conversationId: varchar("conversation_id").primaryKey().notNull(),
	specJson: text("spec_json").notNull(),
	updatedAt: varchar("updated_at").notNull(),
});

export const permissionRequests = pgTable("permission_requests", {
	requestId: varchar("request_id").primaryKey().notNull(),
	conversationId: varchar("conversation_id").notNull(),
	targetAccount: varchar("target_account").notNull(),
	justification: text().notNull(),
	status: varchar().notNull(),
	riskLevel: varchar("risk_level").notNull(),
	policyDocument: text("policy_document"),
	managedPolicyArns: text("managed_policy_arns").notNull(),
	policySummary: text("policy_summary").notNull(),
	conversationUrl: text("conversation_url"),
	parentRequestId: varchar("parent_request_id"),
	requestedAt: varchar("requested_at").notNull(),
	approvedAt: varchar("approved_at"),
	approvedBy: varchar("approved_by"),
	deniedAt: varchar("denied_at"),
	deniedBy: varchar("denied_by"),
	denyReason: text("deny_reason"),
	revokedAt: varchar("revoked_at"),
	iamRoleArn: varchar("iam_role_arn"),
	iamPolicyArn: varchar("iam_policy_arn"),
	roleExpiresAt: varchar("role_expires_at"),
	credentialsIssuedAt: varchar("credentials_issued_at"),
	expiresAt: varchar("expires_at"),
}, (table) => [
	index("ix_permission_requests_conversation_id").using("btree", table.conversationId.asc().nullsLast().op("text_ops")),
	index("ix_permission_requests_status").using("btree", table.status.asc().nullsLast().op("text_ops")),
	index("ix_permission_requests_target_account").using("btree", table.targetAccount.asc().nullsLast().op("text_ops")),
]);

export const moduleRegistry = pgTable("module_registry", {
	id: serial().primaryKey().notNull(),
	name: varchar().notNull(),
	owner: varchar().notNull(),
	description: text().notNull(),
	visibility: varchar().notNull(),
	version: integer().notNull(),
	filesJson: text("files_json").notNull(),
	createdAt: varchar("created_at").notNull(),
	updatedAt: varchar("updated_at").notNull(),
}, (table) => [
	uniqueIndex("ix_module_registry_name").using("btree", table.name.asc().nullsLast().op("text_ops")),
	index("ix_module_registry_owner").using("btree", table.owner.asc().nullsLast().op("text_ops")),
	index("ix_module_registry_visibility").using("btree", table.visibility.asc().nullsLast().op("text_ops")),
]);
