// @generated by `just db-generate` from lib/sql/byoc/schema.sql — do not edit.
// Regenerate after a schema change; CI fails on drift (just db-generate-check).

import { pgTable, text, timestamp } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"



export const remoteAgents = pgTable("remote_agents", {
	owner: text().primaryKey().notNull(),
	status: text().default('offline').notNull(),
	lastSeen: timestamp("last_seen", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	sessionId: text("session_id"),
});
