// @generated by `just db-generate` from lib/sql/byoc/schema.sql — do not edit.
// Regenerate after a schema change; CI fails on drift (just db-generate-check).

import { pgTable, text, timestamp, index } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"



export const remoteAgents = pgTable("remote_agents", {
	owner: text().primaryKey().notNull(),
	status: text().default('offline').notNull(),
	lastSeen: timestamp("last_seen", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	sessionId: text("session_id"),
});

export const remoteAgentDevices = pgTable("remote_agent_devices", {
	id: text().primaryKey().notNull(),
	owner: text().notNull(),
	publicKey: text("public_key").notNull(),
	label: text(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	lastSeen: timestamp("last_seen", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("remote_agent_devices_owner_idx").using("btree", table.owner.asc().nullsLast().op("text_ops")),
]);
