// @generated by `just db-generate` from lib/sql/scheduler/schema.sql — do not edit.
// Regenerate after a schema change; CI fails on drift (just db-generate-check).

import { pgTable, varchar, text, boolean, timestamp, foreignKey } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"



export const scheduledTasks = pgTable("scheduled_tasks", {
	id: varchar().primaryKey().notNull(),
	title: text().notNull(),
	prompt: text().notNull(),
	cron: varchar().notNull(),
	timezone: varchar().notNull(),
	owner: varchar().notNull(),
	enabled: boolean().notNull(),
	nextRunAt: timestamp("next_run_at", { withTimezone: true, mode: 'string' }),
	lastRunAt: timestamp("last_run_at", { withTimezone: true, mode: 'string' }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const taskRuns = pgTable("task_runs", {
	id: varchar().primaryKey().notNull(),
	taskId: varchar("task_id").notNull(),
	conversationId: varchar("conversation_id"),
	status: varchar().notNull(),
	error: text(),
	firedAt: timestamp("fired_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.taskId],
			foreignColumns: [scheduledTasks.id],
			name: "task_runs_task_id_fkey"
		}).onDelete("cascade"),
]);
