// @generated by `just db-generate` from lib/sql/webhooks/schema.sql — do not edit.
// Regenerate after a schema change; CI fails on drift (just db-generate-check).

import { pgTable, unique, serial, varchar, integer, timestamp, text, index } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"



export const conversationMap = pgTable("conversation_map", {
	id: serial().primaryKey().notNull(),
	source: varchar().notNull(),
	resourceType: varchar("resource_type").notNull(),
	resourceId: varchar("resource_id").notNull(),
	conversationId: varchar("conversation_id").notNull(),
	projectId: integer("project_id"),
	noteableType: varchar("noteable_type"),
	noteableIid: integer("noteable_iid"),
	noteId: integer("note_id"),
	lastStatus: varchar("last_status"),
	slackChannel: varchar("slack_channel"),
	slackTs: varchar("slack_ts"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	unique("conversation_map_source_resource_type_resource_id_key").on(table.source, table.resourceType, table.resourceId),
]);

export const jiraTickets = pgTable("jira_tickets", {
	id: serial().primaryKey().notNull(),
	conversationId: varchar("conversation_id").notNull(),
	issueKey: varchar("issue_key").notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	unique("jira_tickets_issue_key_key").on(table.issueKey),
]);

export const resourceLinks = pgTable("resource_links", {
	id: serial().primaryKey().notNull(),
	conversationId: varchar("conversation_id").notNull(),
	source: varchar().notNull(),
	resourceType: varchar("resource_type").notNull(),
	resourceId: varchar("resource_id").notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	unique("resource_links_source_resource_type_resource_id_key").on(table.source, table.resourceType, table.resourceId),
]);

export const pendingMessages = pgTable("pending_messages", {
	id: serial().primaryKey().notNull(),
	source: varchar().notNull(),
	resourceType: varchar("resource_type").notNull(),
	resourceId: varchar("resource_id").notNull(),
	message: text().notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const userIdentity = pgTable("user_identity", {
	id: text().primaryKey().notNull(),
	email: text(),
	name: text(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("user_identity_email_lower").using("btree", sql`lower(email)`),
]);
