#!/usr/bin/env bash
# db-generate.sh — regenerate everything derived from the schema spec.
#
# TWO sources, in order:
#
#   1. The `agentSandbox.db` MODULE OPTION (#606) — the topology: which databases
#      exist, which tables are in each, who writes and who reads. From it:
#        - lib/sql/owners.toml     the ownership manifest
#        - lib/sql/atlas.hcl       one Atlas env per database
#      owners.toml's top-level `[<database>]` sections ARE the database list, which
#      this script and the justfile read back rather than keeping a third artifact.
#      These used to be five hand-maintained lists (here, the justfile, atlas.hcl,
#      db-migrate.nix's `candidates`, guard.ts's DATABASES) that nothing checked
#      against each other.
#
#   2. lib/sql/<db>/schema.sql — the DDL. From it:
#        - lib/ts/scooter-schema/src/<db>.ts   (Drizzle, via drizzle-kit pull)
#        - lib/py/scooter-schema/src/scooter_schema/<db>.py (SQLAlchemy, via sqlacodegen)
#
# Step 1 must run first: the database list it writes is what step 2 iterates.
#
# Neither generator touches a real/shared Postgres: the schema is loaded into an
# EMBEDDED pglite (WASM Postgres). drizzle-kit pulls from a pglite data dir; for
# SQLAlchemy the same pglite is exposed on a loopback socket that sqlacodegen
# introspects. Each run is fully isolated, so concurrent CI jobs never interfere.
#
# Regenerate whenever a schema.sql changes; `just db-generate-check` fails CI if the
# committed output drifts from what this produces.
#
# Needs: node + npx (drizzle-kit, @electric-sql/pglite[-socket] from the workspace
# install) and uv (runs a pinned sqlacodegen). Run from the repo root.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

# --- step 1: render the spec artifacts from the module system ----------------
# Built, not evaluated with `nix eval`, so both files come out of one
# derivation and can't disagree with each other.
echo "rendering lib/sql spec artifacts from agentSandbox.db ..."
spec="$(nix build --no-link --print-out-paths "$ROOT#db-spec")"
install -m 644 "$spec/owners.toml"    lib/sql/owners.toml
install -m 644 "$spec/atlas.hcl"      lib/sql/atlas.hcl

# The database set, read back out of the manifest we just wrote — no third artifact.
ENVS="$(sed -n 's/^\[\([a-z_][a-z_0-9]*\)\]$/\1/p' lib/sql/owners.toml | tr '\n' ' ')"
TS_OUT="lib/ts/scooter-schema/src"
PY_OUT="lib/py/scooter-schema/src/scooter_schema"
SQLACODEGEN_VERSION="4.0.4"
# …and SQLAlchemy, which sqlacodegen does NOT pin. The generated annotation for a
# JSONB column is SQLAlchemy's `JSONB.python_type`, and 2.1.0 (2026-09-24) changed
# it from `dict` to `object` — so main went red with no commit behind it, on a
# required check, from an upstream release alone. Pinning the tool is not enough
# when the tool's dependency decides the output.
#
# 2.0.54 is the newest 2.0.x, i.e. the latest release that still reproduces the
# committed bindings. Bump deliberately: raise this, regenerate, review the diff.
SQLALCHEMY_VERSION="2.0.54"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

ts_header() { printf '// @generated by `just db-generate` from lib/sql/%s/schema.sql — do not edit.\n// Regenerate after a schema change; CI fails on drift (just db-generate-check).\n\n' "$1"; }
py_header() { printf '# @generated by `just db-generate` from lib/sql/%s/schema.sql — do not edit.\n# Regenerate after a schema change; CI fails on drift (just db-generate-check).\n\n' "$1"; }

for env in $ENVS; do
  schema="$ROOT/lib/sql/$env/schema.sql"
  echo "generating $env ..."

  # --- TypeScript (Drizzle) --------------------------------------------------
  # Load schema.sql into a throwaway pglite data dir, then drizzle-kit pull.
  datadir="$work/pg-$env"
  node -e "import('@electric-sql/pglite').then(async ({ PGlite }) => {
    const db = new PGlite('$datadir');
    await db.exec(require('fs').readFileSync('$schema', 'utf8'));
    await db.close();
  })"
  # Plain object (no `defineConfig` import) so the config resolves no modules from
  # its temp-dir location.
  cat > "$work/drizzle-$env.config.ts" <<CFG
export default {
  dialect: 'postgresql',
  driver: 'pglite',
  dbCredentials: { url: '$datadir' },
  schema: './unused.ts',
  out: '$work/dz-$env',
};
CFG
  npx --no-install drizzle-kit pull --config="$work/drizzle-$env.config.ts" >/dev/null
  { ts_header "$env"; cat "$work/dz-$env/schema.ts"; } > "$TS_OUT/$env.ts"

  # --- Python (SQLAlchemy) ---------------------------------------------------
  # Expose the same schema from pglite on a loopback socket; sqlacodegen introspects it.
  port=$(( (RANDOM % 20000) + 20000 ))
  node -e "
    const { PGlite } = require('@electric-sql/pglite');
    const { PGLiteSocketServer } = require('@electric-sql/pglite-socket');
    (async () => {
      const db = new PGlite();
      await db.exec(require('fs').readFileSync('$schema', 'utf8'));
      const server = new PGLiteSocketServer({ db, port: $port, host: '127.0.0.1' });
      await server.start();
      process.stdout.write('READY');
    })();
  " > "$work/sock-$env.log" 2>"$work/sock-$env.err" &
  sockpid=$!
  for _ in $(seq 1 60); do grep -q READY "$work/sock-$env.log" 2>/dev/null && break; sleep 0.25; done
  uv run --quiet --with "sqlacodegen==$SQLACODEGEN_VERSION" \
    --with "sqlalchemy==$SQLALCHEMY_VERSION" --with psycopg2-binary \
    sqlacodegen "postgresql+psycopg2://postgres@127.0.0.1:$port/postgres" > "$work/models-$env.py"
  kill "$sockpid" 2>/dev/null || true
  wait "$sockpid" 2>/dev/null || true
  { py_header "$env"; cat "$work/models-$env.py"; } > "$PY_OUT/$env.py"
done

echo "generated: $TS_OUT/{$(echo "$ENVS" | tr ' ' ,)}.ts and $PY_OUT/{$(echo "$ENVS" | tr ' ' ,)}.py"
