#!/usr/bin/env bash
# db-generate.sh — regenerate the per-language ORM bindings from lib/sql.
#
# The single source of truth is lib/sql/<db>/schema.sql. This script derives:
#   - lib/ts/scooter-schema/src/<db>.ts   (Drizzle, via drizzle-kit pull)
#   - lib/py/scooter-schema/src/scooter_schema/<db>.py (SQLAlchemy, via sqlacodegen)
#
# Neither generator touches a real/shared Postgres: the schema is loaded into an
# EMBEDDED pglite (WASM Postgres). drizzle-kit pulls from a pglite data dir; for
# SQLAlchemy the same pglite is exposed on a loopback socket that sqlacodegen
# introspects. Each run is fully isolated, so concurrent CI jobs never interfere.
#
# Regenerate whenever a schema.sql changes; `just db-generate-check` fails CI if the
# committed output drifts from what this produces.
#
# Needs: node + npx (drizzle-kit, @electric-sql/pglite[-socket] from the workspace
# install) and uv (runs a pinned sqlacodegen). Run from the repo root.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
ENVS="webhooks scheduler broker byoc agent_host"
TS_OUT="lib/ts/scooter-schema/src"
PY_OUT="lib/py/scooter-schema/src/scooter_schema"
SQLACODEGEN_VERSION="4.0.4"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

ts_header() { printf '// @generated by `just db-generate` from lib/sql/%s/schema.sql — do not edit.\n// Regenerate after a schema change; CI fails on drift (just db-generate-check).\n\n' "$1"; }
py_header() { printf '# @generated by `just db-generate` from lib/sql/%s/schema.sql — do not edit.\n# Regenerate after a schema change; CI fails on drift (just db-generate-check).\n\n' "$1"; }

for env in $ENVS; do
  schema="$ROOT/lib/sql/$env/schema.sql"
  echo "generating $env ..."

  # --- TypeScript (Drizzle) --------------------------------------------------
  # Load schema.sql into a throwaway pglite data dir, then drizzle-kit pull.
  datadir="$work/pg-$env"
  node -e "import('@electric-sql/pglite').then(async ({ PGlite }) => {
    const db = new PGlite('$datadir');
    await db.exec(require('fs').readFileSync('$schema', 'utf8'));
    await db.close();
  })"
  # Plain object (no `defineConfig` import) so the config resolves no modules from
  # its temp-dir location.
  cat > "$work/drizzle-$env.config.ts" <<CFG
export default {
  dialect: 'postgresql',
  driver: 'pglite',
  dbCredentials: { url: '$datadir' },
  schema: './unused.ts',
  out: '$work/dz-$env',
};
CFG
  npx --no-install drizzle-kit pull --config="$work/drizzle-$env.config.ts" >/dev/null
  { ts_header "$env"; cat "$work/dz-$env/schema.ts"; } > "$TS_OUT/$env.ts"

  # --- Python (SQLAlchemy) ---------------------------------------------------
  # Expose the same schema from pglite on a loopback socket; sqlacodegen introspects it.
  port=$(( (RANDOM % 20000) + 20000 ))
  node -e "
    const { PGlite } = require('@electric-sql/pglite');
    const { PGLiteSocketServer } = require('@electric-sql/pglite-socket');
    (async () => {
      const db = new PGlite();
      await db.exec(require('fs').readFileSync('$schema', 'utf8'));
      const server = new PGLiteSocketServer({ db, port: $port, host: '127.0.0.1' });
      await server.start();
      process.stdout.write('READY');
    })();
  " > "$work/sock-$env.log" 2>"$work/sock-$env.err" &
  sockpid=$!
  for _ in $(seq 1 60); do grep -q READY "$work/sock-$env.log" 2>/dev/null && break; sleep 0.25; done
  uv run --quiet --with "sqlacodegen==$SQLACODEGEN_VERSION" --with psycopg2-binary \
    sqlacodegen "postgresql+psycopg2://postgres@127.0.0.1:$port/postgres" > "$work/models-$env.py"
  kill "$sockpid" 2>/dev/null || true
  wait "$sockpid" 2>/dev/null || true
  { py_header "$env"; cat "$work/models-$env.py"; } > "$PY_OUT/$env.py"
done

echo "generated: $TS_OUT/{$(echo "$ENVS" | tr ' ' ,)}.ts and $PY_OUT/{$(echo "$ENVS" | tr ' ' ,)}.py"
