# @generated by `just db-generate` from lib/sql/agent_host/schema.sql — do not edit.
# Regenerate after a schema change; CI fails on drift (just db-generate-check).

from typing import Optional
import datetime

from sqlalchemy import BigInteger, Boolean, DateTime, Index, PrimaryKeyConstraint, Text, text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

class Base(DeclarativeBase):
    pass


class ConversationAssets(Base):
    __tablename__ = 'conversation_assets'
    __table_args__ = (
        PrimaryKeyConstraint('conversation_id', 'asset_id', name='conversation_assets_pkey'),
        Index('conversation_assets_by_conv', 'conversation_id'),
        Index('conversation_assets_by_id', 'asset_id')
    )

    conversation_id: Mapped[str] = mapped_column(Text, primary_key=True)
    asset_id: Mapped[str] = mapped_column(Text, primary_key=True)
    mime_type: Mapped[str] = mapped_column(Text, nullable=False)
    size_bytes: Mapped[int] = mapped_column(BigInteger, nullable=False)
    sha256_hash: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text('now()'))


class ConversationEvents(Base):
    __tablename__ = 'conversation_events'
    __table_args__ = (
        PrimaryKeyConstraint('conversation_id', 'seq', name='conversation_events_pkey'),
    )

    conversation_id: Mapped[str] = mapped_column(Text, primary_key=True)
    seq: Mapped[int] = mapped_column(BigInteger, primary_key=True)
    event: Mapped[dict] = mapped_column(JSONB, nullable=False)
    checksum: Mapped[str] = mapped_column(Text, nullable=False)
    prev_checksum: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text('now()'))


class ConversationJobs(Base):
    __tablename__ = 'conversation_jobs'
    __table_args__ = (
        PrimaryKeyConstraint('conversation_id', 'job_id', name='conversation_jobs_pkey'),
        Index('conversation_jobs_by_conv', 'conversation_id', 'started_at')
    )

    conversation_id: Mapped[str] = mapped_column(Text, primary_key=True)
    job_id: Mapped[str] = mapped_column(Text, primary_key=True)
    command: Mapped[str] = mapped_column(Text, nullable=False)
    started_at: Mapped[int] = mapped_column(BigInteger, nullable=False)
    notified_at: Mapped[Optional[int]] = mapped_column(BigInteger)


class Conversations(Base):
    __tablename__ = 'conversations'
    __table_args__ = (
        PrimaryKeyConstraint('id', name='conversations_pkey'),
        Index('conversations_by_activity', 'last_activity_at'),
        Index('conversations_by_owner', 'owner')
    )

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    thread_id: Mapped[str] = mapped_column(Text, nullable=False)
    title: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[int] = mapped_column(BigInteger, nullable=False)
    last_activity_at: Mapped[int] = mapped_column(BigInteger, nullable=False)
    model: Mapped[Optional[str]] = mapped_column(Text)
    owner: Mapped[Optional[str]] = mapped_column(Text)
    parent_id: Mapped[Optional[str]] = mapped_column(Text)
    user_titled: Mapped[Optional[bool]] = mapped_column(Boolean)
    starred: Mapped[Optional[bool]] = mapped_column(Boolean)
    pending_queue: Mapped[Optional[dict]] = mapped_column(JSONB)
