# @generated by `just db-generate` from lib/sql/agent_host/schema.sql — do not edit.
# Regenerate after a schema change; CI fails on drift (just db-generate-check).

from typing import Optional

from sqlalchemy import BigInteger, Boolean, Index, PrimaryKeyConstraint, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

class Base(DeclarativeBase):
    pass


class ConversationJobs(Base):
    __tablename__ = 'conversation_jobs'
    __table_args__ = (
        PrimaryKeyConstraint('conversation_id', 'job_id', name='conversation_jobs_pkey'),
        Index('conversation_jobs_by_conv', 'conversation_id', 'started_at')
    )

    conversation_id: Mapped[str] = mapped_column(Text, primary_key=True)
    job_id: Mapped[str] = mapped_column(Text, primary_key=True)
    command: Mapped[str] = mapped_column(Text, nullable=False)
    started_at: Mapped[int] = mapped_column(BigInteger, nullable=False)
    notified_at: Mapped[Optional[int]] = mapped_column(BigInteger)


class Conversations(Base):
    __tablename__ = 'conversations'
    __table_args__ = (
        PrimaryKeyConstraint('id', name='conversations_pkey'),
        Index('conversations_by_activity', 'last_activity_at'),
        Index('conversations_by_owner', 'owner')
    )

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    thread_id: Mapped[str] = mapped_column(Text, nullable=False)
    title: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[int] = mapped_column(BigInteger, nullable=False)
    last_activity_at: Mapped[int] = mapped_column(BigInteger, nullable=False)
    model: Mapped[Optional[str]] = mapped_column(Text)
    owner: Mapped[Optional[str]] = mapped_column(Text)
    parent_id: Mapped[Optional[str]] = mapped_column(Text)
    user_titled: Mapped[Optional[bool]] = mapped_column(Boolean)
    starred: Mapped[Optional[bool]] = mapped_column(Boolean)
    pending_queue: Mapped[Optional[dict]] = mapped_column(JSONB)
