# @generated by `just db-generate` from lib/sql/broker/schema.sql — do not edit.
# Regenerate after a schema change; CI fails on drift (just db-generate-check).

from typing import Optional

from sqlalchemy import Index, Integer, PrimaryKeyConstraint, String, Text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

class Base(DeclarativeBase):
    pass


class ModuleRegistry(Base):
    __tablename__ = 'module_registry'
    __table_args__ = (
        PrimaryKeyConstraint('id', name='module_registry_pkey'),
        Index('ix_module_registry_name', 'name', unique=True),
        Index('ix_module_registry_owner', 'owner'),
        Index('ix_module_registry_visibility', 'visibility')
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    name: Mapped[str] = mapped_column(String, nullable=False)
    owner: Mapped[str] = mapped_column(String, nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    visibility: Mapped[str] = mapped_column(String, nullable=False)
    version: Mapped[int] = mapped_column(Integer, nullable=False)
    files_json: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[str] = mapped_column(String, nullable=False)
    updated_at: Mapped[str] = mapped_column(String, nullable=False)


class PermissionRequests(Base):
    __tablename__ = 'permission_requests'
    __table_args__ = (
        PrimaryKeyConstraint('request_id', name='permission_requests_pkey'),
        Index('ix_permission_requests_conversation_id', 'conversation_id'),
        Index('ix_permission_requests_status', 'status'),
        Index('ix_permission_requests_target_account', 'target_account')
    )

    request_id: Mapped[str] = mapped_column(String, primary_key=True)
    conversation_id: Mapped[str] = mapped_column(String, nullable=False)
    target_account: Mapped[str] = mapped_column(String, nullable=False)
    justification: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(String, nullable=False)
    risk_level: Mapped[str] = mapped_column(String, nullable=False)
    managed_policy_arns: Mapped[str] = mapped_column(Text, nullable=False)
    policy_summary: Mapped[str] = mapped_column(Text, nullable=False)
    requested_at: Mapped[str] = mapped_column(String, nullable=False)
    policy_document: Mapped[Optional[str]] = mapped_column(Text)
    conversation_url: Mapped[Optional[str]] = mapped_column(Text)
    parent_request_id: Mapped[Optional[str]] = mapped_column(String)
    approved_at: Mapped[Optional[str]] = mapped_column(String)
    approved_by: Mapped[Optional[str]] = mapped_column(String)
    denied_at: Mapped[Optional[str]] = mapped_column(String)
    denied_by: Mapped[Optional[str]] = mapped_column(String)
    deny_reason: Mapped[Optional[str]] = mapped_column(Text)
    revoked_at: Mapped[Optional[str]] = mapped_column(String)
    iam_role_arn: Mapped[Optional[str]] = mapped_column(String)
    iam_policy_arn: Mapped[Optional[str]] = mapped_column(String)
    role_expires_at: Mapped[Optional[str]] = mapped_column(String)
    credentials_issued_at: Mapped[Optional[str]] = mapped_column(String)
    expires_at: Mapped[Optional[str]] = mapped_column(String)


class SandboxSize(Base):
    __tablename__ = 'sandbox_size'
    __table_args__ = (
        PrimaryKeyConstraint('conversation_id', name='sandbox_size_pkey'),
    )

    conversation_id: Mapped[str] = mapped_column(String, primary_key=True)
    spec_json: Mapped[str] = mapped_column(Text, nullable=False)
    updated_at: Mapped[str] = mapped_column(String, nullable=False)


class StaticShareVersions(Base):
    __tablename__ = 'static_share_versions'
    __table_args__ = (
        PrimaryKeyConstraint('id', name='static_share_versions_pkey'),
        Index('ix_static_share_versions_share_uuid', 'share_uuid')
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    share_uuid: Mapped[str] = mapped_column(String, nullable=False)
    version: Mapped[int] = mapped_column(Integer, nullable=False)
    entry_point: Mapped[str] = mapped_column(String, nullable=False)
    files_json: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[str] = mapped_column(String, nullable=False)


class StaticShares(Base):
    __tablename__ = 'static_shares'
    __table_args__ = (
        PrimaryKeyConstraint('uuid', name='static_shares_pkey'),
        Index('ix_static_shares_conversation_id', 'conversation_id'),
        Index('ix_static_shares_owner', 'owner'),
        Index('ix_static_shares_visibility', 'visibility')
    )

    uuid: Mapped[str] = mapped_column(String, primary_key=True)
    owner: Mapped[str] = mapped_column(String, nullable=False)
    conversation_id: Mapped[str] = mapped_column(String, nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    visibility: Mapped[str] = mapped_column(String, nullable=False)
    latest_version: Mapped[int] = mapped_column(Integer, nullable=False)
    created_at: Mapped[str] = mapped_column(String, nullable=False)
    updated_at: Mapped[str] = mapped_column(String, nullable=False)
