# @generated by `just db-generate` from lib/sql/byoc/schema.sql — do not edit.
# Regenerate after a schema change; CI fails on drift (just db-generate-check).

from typing import Optional
import datetime

from sqlalchemy import DateTime, Index, PrimaryKeyConstraint, Text, text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

class Base(DeclarativeBase):
    pass


class RemoteAgentDevices(Base):
    __tablename__ = 'remote_agent_devices'
    __table_args__ = (
        PrimaryKeyConstraint('id', name='remote_agent_devices_pkey'),
        Index('remote_agent_devices_owner_idx', 'owner')
    )

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    owner: Mapped[str] = mapped_column(Text, nullable=False)
    public_key: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text('now()'))
    last_seen: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text('now()'))
    label: Mapped[Optional[str]] = mapped_column(Text)


class RemoteAgents(Base):
    __tablename__ = 'remote_agents'
    __table_args__ = (
        PrimaryKeyConstraint('owner', name='remote_agents_pkey'),
    )

    owner: Mapped[str] = mapped_column(Text, primary_key=True)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'offline'::text"))
    last_seen: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text('now()'))
    session_id: Mapped[Optional[str]] = mapped_column(Text)
