# @generated by `just db-generate` from lib/sql/scheduler/schema.sql — do not edit.
# Regenerate after a schema change; CI fails on drift (just db-generate-check).

from typing import Optional
import datetime

from sqlalchemy import Boolean, DateTime, ForeignKeyConstraint, PrimaryKeyConstraint, String, Text, text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

class Base(DeclarativeBase):
    pass


class ScheduledTasks(Base):
    __tablename__ = 'scheduled_tasks'
    __table_args__ = (
        PrimaryKeyConstraint('id', name='scheduled_tasks_pkey'),
    )

    id: Mapped[str] = mapped_column(String, primary_key=True)
    title: Mapped[str] = mapped_column(Text, nullable=False)
    prompt: Mapped[str] = mapped_column(Text, nullable=False)
    cron: Mapped[str] = mapped_column(String, nullable=False)
    timezone: Mapped[str] = mapped_column(String, nullable=False)
    owner: Mapped[str] = mapped_column(String, nullable=False)
    enabled: Mapped[bool] = mapped_column(Boolean, nullable=False)
    created_at: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text('now()'))
    updated_at: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text('now()'))
    next_run_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True))
    last_run_at: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True))

    task_runs: Mapped[list['TaskRuns']] = relationship('TaskRuns', back_populates='task')


class TaskRuns(Base):
    __tablename__ = 'task_runs'
    __table_args__ = (
        ForeignKeyConstraint(['task_id'], ['scheduled_tasks.id'], ondelete='CASCADE', name='task_runs_task_id_fkey'),
        PrimaryKeyConstraint('id', name='task_runs_pkey')
    )

    id: Mapped[str] = mapped_column(String, primary_key=True)
    task_id: Mapped[str] = mapped_column(String, nullable=False)
    status: Mapped[str] = mapped_column(String, nullable=False)
    fired_at: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text('now()'))
    conversation_id: Mapped[Optional[str]] = mapped_column(String)
    error: Mapped[Optional[str]] = mapped_column(Text)

    task: Mapped['ScheduledTasks'] = relationship('ScheduledTasks', back_populates='task_runs')
