# @generated by `just db-generate` from lib/sql/webhooks/schema.sql — do not edit.
# Regenerate after a schema change; CI fails on drift (just db-generate-check).

from typing import Optional
import datetime

from sqlalchemy import DateTime, Index, Integer, PrimaryKeyConstraint, String, Text, UniqueConstraint, text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

class Base(DeclarativeBase):
    pass


class ConversationMap(Base):
    __tablename__ = 'conversation_map'
    __table_args__ = (
        PrimaryKeyConstraint('id', name='conversation_map_pkey'),
        UniqueConstraint('source', 'resource_type', 'resource_id', name='conversation_map_source_resource_type_resource_id_key')
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    source: Mapped[str] = mapped_column(String, nullable=False)
    resource_type: Mapped[str] = mapped_column(String, nullable=False)
    resource_id: Mapped[str] = mapped_column(String, nullable=False)
    conversation_id: Mapped[str] = mapped_column(String, nullable=False)
    created_at: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text('now()'))
    project_id: Mapped[Optional[int]] = mapped_column(Integer)
    noteable_type: Mapped[Optional[str]] = mapped_column(String)
    noteable_iid: Mapped[Optional[int]] = mapped_column(Integer)
    note_id: Mapped[Optional[int]] = mapped_column(Integer)
    last_status: Mapped[Optional[str]] = mapped_column(String)
    slack_channel: Mapped[Optional[str]] = mapped_column(String)
    slack_ts: Mapped[Optional[str]] = mapped_column(String)


class CredentialScopes(Base):
    __tablename__ = 'credential_scopes'
    __table_args__ = (
        PrimaryKeyConstraint('id', name='credential_scopes_pkey'),
        UniqueConstraint('conversation_id', 'provider', 'scope', name='credential_scopes_conversation_id_provider_scope_key')
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    conversation_id: Mapped[str] = mapped_column(String, nullable=False)
    provider: Mapped[str] = mapped_column(String, nullable=False)
    scope: Mapped[str] = mapped_column(String, nullable=False)
    created_at: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text('now()'))


class JiraTickets(Base):
    __tablename__ = 'jira_tickets'
    __table_args__ = (
        PrimaryKeyConstraint('id', name='jira_tickets_pkey'),
        UniqueConstraint('issue_key', name='jira_tickets_issue_key_key')
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    conversation_id: Mapped[str] = mapped_column(String, nullable=False)
    issue_key: Mapped[str] = mapped_column(String, nullable=False)
    created_at: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text('now()'))


class PendingMessages(Base):
    __tablename__ = 'pending_messages'
    __table_args__ = (
        PrimaryKeyConstraint('id', name='pending_messages_pkey'),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    source: Mapped[str] = mapped_column(String, nullable=False)
    resource_type: Mapped[str] = mapped_column(String, nullable=False)
    resource_id: Mapped[str] = mapped_column(String, nullable=False)
    message: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text('now()'))


class RemoteAgents(Base):
    __tablename__ = 'remote_agents'
    __table_args__ = (
        PrimaryKeyConstraint('owner', name='remote_agents_pkey'),
    )

    owner: Mapped[str] = mapped_column(Text, primary_key=True)
    status: Mapped[str] = mapped_column(Text, nullable=False, server_default=text("'offline'::text"))
    last_seen: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text('now()'))


class ResourceLinks(Base):
    __tablename__ = 'resource_links'
    __table_args__ = (
        PrimaryKeyConstraint('id', name='resource_links_pkey'),
        UniqueConstraint('source', 'resource_type', 'resource_id', name='resource_links_source_resource_type_resource_id_key')
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    conversation_id: Mapped[str] = mapped_column(String, nullable=False)
    source: Mapped[str] = mapped_column(String, nullable=False)
    resource_type: Mapped[str] = mapped_column(String, nullable=False)
    resource_id: Mapped[str] = mapped_column(String, nullable=False)
    created_at: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text('now()'))


class UserIdentity(Base):
    __tablename__ = 'user_identity'
    __table_args__ = (
        PrimaryKeyConstraint('id', name='user_identity_pkey'),
        Index('user_identity_email_lower')
    )

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    updated_at: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text('now()'))
    email: Mapped[Optional[str]] = mapped_column(Text)
    name: Mapped[Optional[str]] = mapped_column(Text)
